pipeline {
    agent any

    environment {
        SERVICE_NAME = 'adservice'
        DOCKER_USERNAME = 'obusorezekiel'
        DOCKER_IMAGE = 'adservice'
        SONARQUBE_PROJECT_ID = 'adservice'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    script {
                        def scannerHome = tool 'SonarQubeScanner'
                        dir("src/${SERVICE_NAME}") {
                            sh "chmod +x gradlew"
                            sh "./gradlew clean"
                            sh "./gradlew sonar -PjavaVersion=17 -Dsonar.projectKey=${SONARQUBE_PROJECT_ID}"
                        }
                    }
                }
            }
        }
    }
}
